# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-01 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdbid',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='id на imdb'),
        ),
    ]
