# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-18 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='dislike',
            field=models.BooleanField(default=False, verbose_name='Если true - like, false - dislike, None - not set'),
        ),
        migrations.AddField(
            model_name='movie',
            name='like',
            field=models.BooleanField(default=False, verbose_name='Если true - like, false - dislike, None - not set'),
        ),
    ]
