# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-29 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20170729_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdbid', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=30)),
                ('face', models.CharField(blank=True, max_length=128, verbose_name="часть url'a для постера")),
            ],
        ),
    ]
