# Generated by Django 3.0.3 on 2020-02-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20170802_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='permanent',
            field=models.BooleanField(default=False, help_text='Предустановленные теги, не могут быть удалены'),
        ),
        migrations.AddField(
            model_name='tag',
            name='permanent_custom_name',
            field=models.CharField(default=False, max_length=30),
            preserve_default=False,
        ),
    ]
