# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-30 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20170730_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='persons',
            field=models.ManyToManyField(to='movie.Person'),
        ),
    ]
