# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-30 10:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie', '0006_person_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='tmdbid',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='movie',
            unique_together=set([('tmdbid', 'user')]),
        ),
    ]
