# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-30 12:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie', '0007_auto_20170730_1044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильмы'},
        ),
        migrations.AlterField(
            model_name='person',
            name='tmdbid',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together=set([('tmdbid', 'user')]),
        ),
    ]
